name: Send Email on Push

on:
  push:
    branches:
      - main  

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          from: veronika.milovzorova@gmail.com
          to: dyer67225@gmail.com

          subject: "Push tehtud repositooriumis ${{ github.repository }}"
          body: |
            Repositoorium ${{ github.repository }} sai uue pushi.
            Pushe tegi: ${{ github.event.pusher.name }}
            Commiti sõnum: ${{ github.event.head_commit.message }}

          secure: true
          #workflow
          #workflow
          #workflow
          #workflow

